services:

  reactapp:
    container_name: react_dev
    image: contone
    build: .
    volumes:
      - ./:/app
    ports:
      - 3001:3000
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true # we need this, without it react hold reaload does not work in docker
      - WATCHPACK_POLLING=true # we need this, without it react hold reaload does not work in docker
      - WDS_SOCKET_HOST=3000 # we may b
      - FAST_REFRESH=false